# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Research Stuff &mdash; Pat Morin
email: morin@scs.carleton.ca
description: > # this means to ignore newlines until "baseurl:"
  A site I use for keeping track of open problems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://patmorin.github.io" # the base hostname & protocol for your site
#twitter_username: devnull
github_username:  patmorin

exclude: [Hyphenate]

#gems:
#  - jekyll-last-modified-at

# Build settings
markdown: kramdown

collections:
  problems:
    output: true
    sort_by: title
  projects:
    output: true
    sort_by: date
