# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pat Morin's Open Problems
email: morin@scs.carleton.ca
description: > # this means to ignore newlines until "baseurl:"
  This is a site I use for keeping track of open problems. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://patmorin.github.io" # the base hostname & protocol for your site
#twitter_username: devnull
github_username:  patmorin

# Build settings
markdown: kramdown
